"""add user table

Revision ID: 8e544629bedf
Revises: 
Create Date: 2024-11-30 22:20:51.402284

"""
from typing import Sequence, Union

from alembic.op import create_table, drop_table, add_column, create_foreign_key, drop_constraint, drop_column
from sqlalchemy import Column, ForeignKey, Integer, String, ForeignKeyConstraint, PrimaryKeyConstraint

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e544629bedf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    create_table(
        "users",
        Column(
            "id", Integer, primary_key=True, nullable=False, autoincrement=True
        ),
        Column("wallet_address", String, nullable=False),
        Column("username", String, unique=True, nullable=False),
        Column("email", String, unique=True, nullable=False),
        Column("hashed_password", String, nullable=False),
        Column("salt", String, nullable=False),
        Column("bio", String, nullable=True),
        Column("profile_pic", String, nullable=True),
        Column("banner", String, nullable=True),
        Column("created_at", sa.DateTime, nullable=False),
    )


def downgrade() -> None:
    drop_table("users")
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
