"""add seller table

Revision ID: a4dc6f2e1702
Revises: e9e516e1b7c7
Create Date: 2024-12-01 11:37:35.853797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, ForeignKey, Integer, String, ForeignKeyConstraint, PrimaryKeyConstraint



# revision identifiers, used by Alembic.
revision: str = 'a4dc6f2e1702'
down_revision: Union[str, None] = 'e9e516e1b7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column("bio", String, nullable=True),
    sa.Column("profile_pic", String, nullable=True),
    sa. Column("banner", String, nullable=True),
    sa.Column("created_at", sa.DateTime, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sellers')
    # ### end Alembic commands ###